#! /bin/sh
# /etc/init.d/tweet-jukebox
 
### BEGIN INIT INFO
# Provides:          tweet-jukebox
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
 
# change this to wherever your node app lives # 
path_to_node_app=/home/pi/workspace/tweet-jukebox/init.js 
 
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "* starting tweet-jukebox * "
    echo "* starting tweet-jukebox * [`date`]" >> /var/log/tweet-jukebox.log
    /usr/local/bin/node $path_to_node_app >> /var/log/tweet-jukebox.log 2>&1&
    ;;
  stop)
    echo "* stopping tweet-jukebox * "
    echo "* stopping tweet-jukebox * [`date`]" >> /var/log/tweet-jukebox.log
    killall /usr/local/bin/node
    ;;
  *)
    echo "Usage: /etc/init.d/tweet-jukebox {start|stop}"
    exit 1
    ;;
esac
 
exit 0
